/**
 * Supported languages for Qwen3-TTS
 * Based on: https://github.com/QwenLM/Qwen3-TTS
 */

export const SUPPORTED_LANGUAGES = {
  zh: 'Chinese',
  en: 'English',
  ja: 'Japanese',
  ko: 'Korean',
  de: 'German',
  fr: 'French',
  ru: 'Russian',
  pt: 'Portuguese',
  es: 'Spanish',
  it: 'Italian',
  
  flemish: 'Flemish',
  abkhaz: 'Abkhaz',
  acehnese: 'Acehnese',
  acholi: 'Acholi',
  afar: 'Afar',
  afrikaans: 'Afrikaans',
  albanian: 'Albanian',
  alur: 'Alur',
  amharic: 'Amharic',
  arabic: 'Arabic',
  armenian: 'Armenian',
  assamese: 'Assamese',
  avar: 'Avar',
  awadhi: 'Awadhi',
  aymara: 'Aymara',
  azerbaijani: 'Azerbaijani',
  balinese: 'Balinese',
  baluchi: 'Baluchi',
  bambara: 'Bambara',
  baoule: 'Baoulé',
  bashkir: 'Bashkir',
  basque: 'Basque',
  batak_karo: 'Batak Karo',
  batak_simalungun: 'Batak Simalungun',
  batak_toba: 'Batak Toba',
  belarusian: 'Belarusian',
  bemba: 'Bemba',
  bengali: 'Bengali',
  betawi: 'Betawi',
  bhojpuri: 'Bhojpuri',
  bikol: 'Bikol',
  bosnian: 'Bosnian',
  breton: 'Breton',
  bulgarian: 'Bulgarian',
  buryat: 'Buryat',
  cantonese: 'Cantonese',
  catalan: 'Catalan',
  cebuano: 'Cebuano',
  chamorro: 'Chamorro',
  chechen: 'Chechen',
  chichewa: 'Chichewa',
  chinese_simplified: 'Chinese (Simplified)',
  chinese_traditional: 'Chinese (Traditional)',
  chuukese: 'Chuukese',
  chuvash: 'Chuvash',
  corsican: 'Corsican',
  crimean_tatar_cyrillic: 'Crimean Tatar (Cyrillic)',
  crimean_tatar_latin: 'Crimean Tatar (Latin)',
  croatian: 'Croatian',
  czech: 'Czech',
  danish: 'Danish',
  dari: 'Dari',
  dhivehi: 'Dhivehi',
  dinka: 'Dinka',
  dogri: 'Dogri',
  dombe: 'Dombe',
  dutch: 'Dutch',
  dyula: 'Dyula',
  dzongkha: 'Dzongkha',
  esperanto: 'Esperanto',
  estonian: 'Estonian',
  ewe: 'Ewe',
  faroese: 'Faroese',
  fijian: 'Fijian',
  filipino: 'Filipino',
  finnish: 'Finnish',
  fon: 'Fon',
  french_canada: 'French (Canada)',
  frisian: 'Frisian',
  friulian: 'Friulian',
  fulani: 'Fulani',
  ga: 'Ga',
  galician: 'Galician',
  georgian: 'Georgian',
  greek: 'Greek',
  guarani: 'Guarani',
  gujarati: 'Gujarati',
  haitian_creole: 'Haitian Creole',
  hakha_chin: 'Hakha Chin',
  hausa: 'Hausa',
  hawaiian: 'Hawaiian',
  hebrew: 'Hebrew',
  hiligaynon: 'Hiligaynon',
  hindi: 'Hindi',
  hmong: 'Hmong',
  hungarian: 'Hungarian',
  hunsrik: 'Hunsrik',
  iban: 'Iban',
  icelandic: 'Icelandic',
  igbo: 'Igbo',
  ilocano: 'Ilocano',
  indonesian: 'Indonesian',
  inuktut_latin: 'Inuktut (Latin)',
  inuktut_syllabics: 'Inuktut (Syllabics)',
  irish: 'Irish',
  jamaican_patois: 'Jamaican Patois',
  javanese: 'Javanese',
  jingpo: 'Jingpo',
  kalaallisut: 'Kalaallisut',
  kannada: 'Kannada',
  kanuri: 'Kanuri',
  kapampangan: 'Kapampangan',
  kazakh: 'Kazakh',
  khasi: 'Khasi',
  khmer: 'Khmer',
  kiga: 'Kiga',
  kikongo: 'Kikongo',
  kinyarwanda: 'Kinyarwanda',
  kituba: 'Kituba',
  kokborok: 'Kokborok',
  komi: 'Komi',
  konkani: 'Konkani',
  krio: 'Krio',
  kurdish_kurmanji: 'Kurdish (Kurmanji)',
  kurdish_sorani: 'Kurdish (Sorani)',
  kyrgyz: 'Kyrgyz',
  lao: 'Lao',
  latgalian: 'Latgalian',
  latin: 'Latin',
  latvian: 'Latvian',
  ligurian: 'Ligurian',
  limburgish: 'Limburgish',
  lingala: 'Lingala',
  lithuanian: 'Lithuanian',
  lombard: 'Lombard',
  luganda: 'Luganda',
  luo: 'Luo',
  luxembourgish: 'Luxembourgish',
  macedonian: 'Macedonian',
  madurese: 'Madurese',
  maithili: 'Maithili',
  makassar: 'Makassar',
  malagasy: 'Malagasy',
  malay: 'Malay',
  malay_jawi: 'Malay (Jawi)',
  malayalam: 'Malayalam',
  maltese: 'Maltese',
  mam: 'Mam',
  manx: 'Manx',
  maori: 'Maori',
  marathi: 'Marathi',
  marshallese: 'Marshallese',
  marwadi: 'Marwadi',
  mauritian_creole: 'Mauritian Creole',
  meadow_mari: 'Meadow Mari',
  meiteilon_manipuri: 'Meiteilon (Manipuri)',
  minang: 'Minang',
  mizo: 'Mizo',
  mongolian: 'Mongolian',
  myanmar_burmese: 'Myanmar (Burmese)',
  nahuatl_eastern_huasteca: 'Nahuatl (Eastern Huasteca)',
  ndau: 'Ndau',
  ndebele_south: 'Ndebele (South)',
  nepalbhasa_newari: 'Nepalbhasa (Newari)',
  nepali: 'Nepali',
  nko: 'NKo',
  norwegian: 'Norwegian',
  nuer: 'Nuer',
  occitan: 'Occitan',
  odia_oriya: 'Odia (Oriya)',
  oromo: 'Oromo',
  ossetian: 'Ossetian',
  pangasinan: 'Pangasinan',
  papiamento: 'Papiamento',
  pashto: 'Pashto',
  persian: 'Persian',
  polish: 'Polish',
  portuguese_brazil: 'Portuguese (Brazil)',
  portuguese_portugal: 'Portuguese (Portugal)',
  punjabi_gurmukhi: 'Punjabi (Gurmukhi)',
  punjabi_shahmukhi: 'Punjabi (Shahmukhi)',
  quechua: 'Quechua',
  q_eqchi: 'Qʼeqchiʼ',
  romani: 'Romani',
  romanian: 'Romanian',
  rundi: 'Rundi',
  sami_north: 'Sami (North)',
  samoan: 'Samoan',
  sango: 'Sango',
  sanskrit: 'Sanskrit',
  santali_latin: 'Santali (Latin)',
  santali_ol_chiki: 'Santali (Ol Chiki)',
  scots_gaelic: 'Scots Gaelic',
  sepedi: 'Sepedi',
  serbian: 'Serbian',
  sesotho: 'Sesotho',
  seychellois_creole: 'Seychellois Creole',
  shan: 'Shan',
  shona: 'Shona',
  sicilian: 'Sicilian',
  silesian: 'Silesian',
  sindhi: 'Sindhi',
  sinhala: 'Sinhala',
  slovak: 'Slovak',
  slovenian: 'Slovenian',
  somali: 'Somali',
  sundanese: 'Sundanese',
  susu: 'Susu',
  swahili: 'Swahili',
  swati: 'Swati',
  swedish: 'Swedish',
  tahitian: 'Tahitian',
  tajik: 'Tajik',
  tamazight: 'Tamazight',
  tamazight_tifinagh: 'Tamazight (Tifinagh)',
  tamil: 'Tamil',
  tatar: 'Tatar',
  telugu: 'Telugu',
  tetum: 'Tetum',
  thai: 'Thai',
  tibetan: 'Tibetan',
  tigrinya: 'Tigrinya',
  tiv: 'Tiv',
  tok_pisin: 'Tok Pisin',
  tongan: 'Tongan',
  tshiluba: 'Tshiluba',
  tsonga: 'Tsonga',
  tswana: 'Tswana',
  tulu: 'Tulu',
  tumbuka: 'Tumbuka',
  turkish: 'Turkish',
  turkmen: 'Turkmen',
  tuvan: 'Tuvan',
  twi: 'Twi',
  udmurt: 'Udmurt',
  ukrainian: 'Ukrainian',
  urdu: 'Urdu',
  uyghur: 'Uyghur',
  uzbek: 'Uzbek',
  venda: 'Venda',
  venetian: 'Venetian',
  vietnamese: 'Vietnamese',
  waray: 'Waray',
  welsh: 'Welsh',
  wolof: 'Wolof',
  xhosa: 'Xhosa',
  yakut: 'Yakut',
  yiddish: 'Yiddish',
  yoruba: 'Yoruba',
  yucatec_maya: 'Yucatec Maya',
  zapotec: 'Zapotec',
  zulu: 'Zulu',
} as const;

export type LanguageCode = keyof typeof SUPPORTED_LANGUAGES;

export const LANGUAGE_CODES = Object.keys(SUPPORTED_LANGUAGES) as LanguageCode[];

export const LANGUAGE_OPTIONS = LANGUAGE_CODES.map((code) => ({
  value: code,
  label: SUPPORTED_LANGUAGES[code],
}));
